groups:

  - name: requests
    rules:
    - record: requests_per_second
      expr: sum(rate(request_seconds_count[1h]))
    - record: requests_time
      expr: request_seconds_sum / request_seconds_count

  - name: facerestore
    rules:
    - record: face_restore_apply_time
      expr: face_restore_apply_seconds_sum / face_restore_apply_seconds_count
